# Generated by Django 6.0.2 on 2026-07-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('advance', models.PositiveIntegerField(default=0)),
                ('rent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hostal.boy')),
            ],
            options={
                'unique_together': {('boy', 'month', 'year')},
            },
        ),
    ]
